const Bal=(p,o={})=>{const b=V(p,"Balance",{gap:6});T(b,"In this vault",{s:12,f:"$muted"});const r=Fr(b,"Amount row",{gap:8,alignItems:"end"});T(r,"1,250,000",{mono:true,s:o.s||40,w:"600"});T(r,"QC",{mono:true,s:16,f:"$muted"});T(b,"7x8zcyKj…4vjLLh6",{mono:true,s:12,f:"$muted"});return b};
const Acts=(p)=>{const a=Fr(p,"Actions",{width:"fill_container",gap:10});Btn(a,"Deposit",{ghost:true,icon:"arrow-down-to-line",h:44});Btn(a,"Send",{icon:"arrow-up-right",h:44});return a};
const Keys=(p)=>{const k=V(p,"Keys");T(k,"Both keys are needed to move funds",{s:12,f:"$muted"});Row(k,"wallet","Wallet key","Ed25519 · Phantom 9Qx…c4F","OK",{ic:"$accent",rf:"$accent",bold:true});Row(k,"key-round","Hash key","Winternitz · 1,023 left","UNUSED",{ic:"$blue",rf:"$blue",bold:true});return k};
const Hist=(p,n=3)=>{const h=V(p,"History");T(h,"History",{s:12,f:"$muted"});[["arrow-up-right","Sent to Maya","25 Sep · 14:02","−40,000"],["arrow-down-left","Deposit from wallet","24 Sep · 14:02","+1,000,000"],["refresh-cw","Moved from vault #2","23 Sep · 09:47","+250,000"],["lock","Vault created","22 Sep · 18:10","0"],["arrow-up-right","Sent to 9Kf2…aa1P","21 Sep · 11:30","−12,500"]].slice(0,n).forEach(x=>Row(h,...x));return h};
const Side=(p,mode,act="Vault")=>{const full=mode==="full";const s=V(p,"Sidebar",{width:full?240:72,height:"fill_container",gap:4,padding:full?[20,14]:[20,12],fill:"$surface",stroke:"$line",strokeWidth:{right:1},alignItems:full?"start":"center"});
 const lg=H(s,"Brand",{gap:10,padding:[0,6,18,6],justifyContent:full?"start":"center"});Fr(lg,"Logo",{cornerRadius:14,width:28,height:28,fill:{type:"image",url:"quantcoin%20app-assets/logo-64.png",mode:"fill"}});if(full)T(lg,"Quantum Safe",{s:16,w:"600"});
 for(const[i,l]of[["layout-dashboard","Home"],["shield","Vault"],["arrow-up-right","Send"],["qr-code","Receive"],["history","Activity"],["settings","Settings"]]){const on=l===act;const it=H(s,l,{gap:12,padding:full?[10,12]:10,cornerRadius:8,justifyContent:full?"start":"center",...(on?{fill:"#2EE6D61F"}:{}),...(full?{}:{width:48})});I(it,i,{s:18,f:on?"$accent":"$muted"});if(full)T(it,l,{f:on?"$accent":"$text",w:on?"600":"normal"});}
 Fr(s,"Push",{width:"fill_container",height:"fill_container"});
 if(full){const n=H(s,"Net",{gap:8,padding:[10,12],cornerRadius:8,stroke:"$line",strokeWidth:1});Fr(n,"Dot",{width:8,height:8,cornerRadius:4,fill:"$warn"});T(n,"Devnet",{s:12});Sp(n);I(n,"sun-moon",{s:16});}
 else I(s,"sun-moon",{s:18});return s};
const Panel=(p,title,o={})=>{const c=V(p,title,{gap:12,padding:18,cornerRadius:12,fill:"$surface",...o});T(c,title,{s:12,w:"600",f:"$muted",x:{letterSpacing:1}});return c};
