const PART="__P__";const Y=48000+(PART=="b"?1000:0);out=[];let X=0;const nx=w=>{const x=X;X+=w+60;return x};
const WP="#1B2240";
const sbIOS=(p,kind,o={})=>{const s=H(p,"Status bar · iOS "+kind,{padding:[kind=="notch"?12:14,26,6,26],height:kind=="notch"?44:54});const l=Fr(s,"Left",{width:70,gap:4,alignItems:"center"});T(l,"9:41",{name:"Time",w:"600",f:o.f||"$text"});Sp(s);if(kind=="notch"){Fr(s,"Notch",{width:160,height:30,cornerRadius:[0,0,18,18],fill:"#000000"})}else if(!o.noIsland){Fr(s,"Dynamic island",{width:120,height:34,cornerRadius:17,fill:"#000000"})}Sp(s);const r=Fr(s,"Right",{gap:5,alignItems:"center",width:70,justifyContent:"end"});const sg=Fr(r,"Signal",{gap:2,alignItems:"end"});[4,6,8,10].forEach((h,i)=>Fr(sg,"Bar "+(i+1),{width:3,height:h,cornerRadius:1,fill:o.f||"$text"}));I(r,"wifi",{s:14,f:o.f||"$text"});const bt=Fr(r,"Battery",{gap:1,alignItems:"center"});const bd=Fr(bt,"Body",{width:24,height:12,cornerRadius:3,stroke:o.f||"$text",strokeWidth:1,padding:2});Fr(bd,"Level",{width:16,height:8,cornerRadius:1,fill:o.f||"$text"});Fr(bt,"Cap",{width:2,height:4,fill:o.f||"$text"});return s};
const sbAnd=(p,o={})=>{const s=H(p,"Status bar · Android",{padding:[10,20,6,20],height:40,gap:6});T(s,"9:41",{name:"Time",s:13,w:"500",f:o.f||"$text"});if(o.notif){const n=Fr(s,"Notification icons",{gap:4});o.notif.forEach(i=>I(n,i,{s:14,f:o.f||"$text"}))}if(o.chip){const c=Fr(s,"Live update chip",{padding:[2,8],cornerRadius:10,fill:"$accent",gap:4,alignItems:"center"});I(c,"arrow-up-right",{s:12,f:"$ink"});T(c,o.chip,{name:"Text",mono:true,s:11,w:"600",f:"$ink"})}Sp(s);Fr(s,"Punch hole",{width:12,height:12,cornerRadius:6,fill:"#000000"});Sp(s);const r=Fr(s,"Right",{gap:5,alignItems:"center"});I(r,"wifi",{s:14,f:o.f||"$text"});I(r,"signal",{s:14,f:o.f||"$text"});const bt=Fr(r,"Battery",{width:10,height:16,cornerRadius:2,stroke:o.f||"$text",strokeWidth:1,padding:1,alignItems:"end"});Fr(bt,"Level",{width:6,height:11,fill:o.f||"$text"});T(r,"82%",{name:"Pct",s:12,f:o.f||"$text"});return s};
const botIOS=(p,f)=>{const h=H(p,"Bottom · iOS home indicator",{justifyContent:"center",padding:[8,0,8,0],height:34});Fr(h,"Home indicator",{width:134,height:5,cornerRadius:3,fill:f||"$text"});return h};
const botGest=(p,f)=>{const h=H(p,"Bottom · Android gesture handle",{justifyContent:"center",padding:[10,0,10,0],height:24});Fr(h,"Gesture handle",{width:108,height:4,cornerRadius:2,fill:f||"$text"});return h};
const bot3=(p,f)=>{const h=H(p,"Bottom · Android 3-button nav",{justifyContent:"space_around",padding:[0,40],height:48,fill:"#000000"});const b1=Fr(h,"Back",{width:44,height:44,justifyContent:"center",alignItems:"center"});I(b1,"chevron-left",{s:20,f:"#FFFFFF"});const b2=Fr(h,"Home",{width:44,height:44,justifyContent:"center",alignItems:"center"});Fr(b2,"Circle",{width:16,height:16,cornerRadius:8,stroke:"#FFFFFF",strokeWidth:2});const b3=Fr(h,"Recents",{width:44,height:44,justifyContent:"center",alignItems:"center"});Fr(b3,"Square",{width:14,height:14,cornerRadius:2,stroke:"#FFFFFF",strokeWidth:2});return h};
const appBody=(s)=>{const b=V(s,"App content",{gap:14,padding:[8,20,0,20],height:"fill_container"});const h=H(b,"Header",{gap:10});const lg=Fr(h,"Logo",{width:28,height:28,cornerRadius:14,fill:"$accent"});T(h,"Quantum Safe",{name:"Title",s:17,w:"600"});T(b,"In this vault",{name:"Label",s:12,f:"$muted"});T(b,"1,284,000 QC",{name:"Amount",mono:true,s:34,w:"600"});for(let i=0;i<4;i++)Fr(b,"Row "+(i+1),{width:"fill_container",height:44,cornerRadius:10,fill:"$surface"});return b};
const ph=(name,w,h,fn,fill)=>{const s=Screen(name,w,h,nx(w),Y);if(fill)Update(s,{fill});fn(s);Update(s,{placeholder:false});out.push(s);return s};
const coinMini=(p,z)=>{const c=Fr(p,"Coin",{width:z,height:z,cornerRadius:z/2,fill:"$accent",justifyContent:"center",alignItems:"center"});T(c,"QC",{name:"Mark",mono:true,s:Math.round(z*.38),w:"700",f:"$ink"});return c};
const homeGrid=(s,f)=>{const g=V(s,"Home screen apps",{gap:22,padding:[30,28],height:"fill_container"});for(let r=0;r<4;r++){const row=Fr(g,"App row "+(r+1),{width:"fill_container",justifyContent:"space_between"});for(let c=0;c<4;c++){const a=V(row,"App",{width:"fit_content",gap:6,alignItems:"center"});Fr(a,"Icon",{width:60,height:60,cornerRadius:14,fill:r==0&&c==0?"$accent":"#2A3358"});Fr(a,"Name",{width:40,height:6,cornerRadius:3,fill:"#3A4470"})}}return g};

if(PART=="a"){
ph("Chrome · iPhone notch + home indicator",390,844,s=>{sbIOS(s,"notch");appBody(s);botIOS(s)});
ph("Chrome · iPhone Dynamic Island + home indicator",393,852,s=>{sbIOS(s,"island");appBody(s);botIOS(s)});
ph("Chrome · Android punch-hole + gesture handle",412,915,s=>{sbAnd(s);appBody(s);botGest(s)});
ph("Chrome · Android punch-hole + 3-button nav",412,915,s=>{sbAnd(s);appBody(s);bot3(s)});
ph("Chrome · iPhone SE (no notch) + home button",375,667,s=>{const st=H(s,"Status bar · iOS classic",{padding:[4,8],height:20});T(st,"9:41",{name:"Time",s:12,w:"600"});appBody(s);const hb=H(s,"Bottom · safe area 0",{height:8})});
const DI=(s,kind)=>{const top=H(s,"Island area",{justifyContent:"center",padding:[11,0,0,0]});if(kind=="compact"){const i=Fr(top,"Dynamic island · compact",{width:250,height:36,cornerRadius:18,fill:"#000000",padding:[0,8],alignItems:"center"});const L=Fr(i,"Leading",{gap:6,alignItems:"center"});coinMini(L,22);Sp(i);const R=Fr(i,"Trailing",{gap:4,alignItems:"center"});Fr(R,"Ring",{width:18,height:18,cornerRadius:9,stroke:"$accent",strokeWidth:2});T(R,"18/32",{name:"Confirmations",mono:true,s:11,f:"$accent"})}if(kind=="minimal"){const i=Fr(top,"Dynamic island · minimal (split)",{gap:8,alignItems:"center"});Fr(i,"Main pill",{width:126,height:36,cornerRadius:18,fill:"#000000"});const m=Fr(i,"Minimal bubble",{width:36,height:36,cornerRadius:18,fill:"#000000",justifyContent:"center",alignItems:"center"});coinMini(m,20)}if(kind=="expanded"||kind=="done"){const d=kind=="done";const i=V(top,"Dynamic island · expanded",{width:370,gap:10,padding:[14,18,16,18],cornerRadius:40,fill:"#000000"});const r1=H(i,"Top row",{gap:10});coinMini(r1,32);const t=V(r1,"Title",{gap:2});T(t,d?"Sent to Maya":"Sending to Maya",{name:"Title",s:14,w:"600",f:"#FFFFFF"});T(t,d?"Finalized · 2.1 s":"Both keys signed",{name:"Sub",s:12,f:"#9AA3C7"});T(r1,"40,000 QC",{name:"Amount",mono:true,s:15,w:"600",f:d?"#3DDC97":"#FFFFFF"});const tr=Fr(i,"Progress track",{width:"fill_container",height:4,cornerRadius:2,fill:"#2A3358"});Fr(tr,"Progress fill",{width:d?334:190,height:4,cornerRadius:2,fill:d?"#3DDC97":"#2EE6D6"});const r2=H(i,"Bottom row",{gap:8});T(r2,d?"Hash key #742 burned":"Confirming 18 of 32",{name:"Status",mono:true,s:11,f:"#9AA3C7"});Sp(r2);const bt=Fr(r2,"Action",{padding:[6,12],cornerRadius:14,fill:"#2A3358"});T(bt,d?"Receipt":"Open",{name:"Label",s:12,w:"600",f:"#FFFFFF"})}};
for(const k of["compact","expanded","minimal","done"])ph("Live activity · iOS Dynamic Island · "+k,393,420,s=>{DI(s,k);homeGrid(s)},WP);
}
if(PART=="b"){
ph("Live activity · iOS lock screen",393,852,s=>{sbIOS(s,"island",{f:"#FFFFFF"});const c=V(s,"Clock",{alignItems:"center",gap:2,padding:[20,0,30,0]});T(c,"Friday 26 September",{name:"Date",s:17,w:"500",f:"#FFFFFF"});T(c,"14:02",{name:"Time",s:84,w:"600",f:"#FFFFFF"});const st=V(s,"Notification stack",{gap:8,padding:[0,12],height:"fill_container",justifyContent:"end"});const la=V(st,"Live activity card",{gap:10,padding:16,cornerRadius:22,fill:"#0B1020"});const r=H(la,"Top",{gap:10});coinMini(r,34);const t=V(r,"Text",{gap:2});T(t,"Sending 40,000 QC",{name:"Title",w:"600",f:"#FFFFFF"});T(t,"to Maya · both keys signed",{name:"Sub",s:12,f:"#9AA3C7"});T(r,"18/32",{name:"Count",mono:true,s:13,f:"#2EE6D6"});const tr=Fr(la,"Track",{width:"fill_container",height:4,cornerRadius:2,fill:"#2A3358"});Fr(tr,"Fill",{width:200,height:4,cornerRadius:2,fill:"#2EE6D6"});const n=H(st,"Notification · received",{gap:10,padding:14,cornerRadius:22,fill:"#FFFFFF22"});coinMini(n,34);const nt=V(n,"Text",{gap:2});const h=H(nt,"Head");T(h,"Quantum Safe",{name:"App",s:13,w:"600",f:"#FFFFFF"});Sp(h);T(h,"now",{name:"Time",s:12,f:"#C9CFE8"});T(nt,"+2,000 QC arrived from 3Fq…9aZ",{name:"Body",s:13,f:"#FFFFFF"});const bb=H(s,"Lock bottom",{justifyContent:"space_between",padding:[10,46,10,46]});for(const i of["flashlight","camera"]){const x=Fr(bb,i,{width:50,height:50,cornerRadius:25,fill:"#FFFFFF22",justifyContent:"center",alignItems:"center"});I(x,i,{s:20,f:"#FFFFFF"})}botIOS(s,"#FFFFFF")},WP);
ph("Notification · iOS banner (in other app)",393,420,s=>{sbIOS(s,"island",{f:"#FFFFFF"});const n=H(s,"Banner",{gap:10,padding:14,cornerRadius:22,fill:"#2A3358"});Update(n,{width:369});coinMini(n,38);const nt=V(n,"Text",{gap:2});const h=H(nt,"Head");T(h,"Quantum Safe",{name:"App",s:13,w:"600",f:"#FFFFFF"});Sp(h);T(h,"now",{name:"Time",s:12,f:"#9AA3C7"});T(nt,"Send failed",{name:"Title",s:14,w:"600",f:"#FFFFFF"});T(nt,"Hash key mismatch. Nothing moved.",{name:"Body",s:13,f:"#C9CFE8"});homeGrid(s)},WP);
ph("Notification · Android shade with live update",412,915,s=>{sbAnd(s,{f:"#FFFFFF"});const q=V(s,"Quick settings",{gap:10,padding:[8,16]});const r=Fr(q,"Tiles",{width:"fill_container",gap:8});for(const i of["wifi","bluetooth","flashlight","moon"]){const t=Fr(r,"Tile · "+i,{width:"fill_container",height:52,cornerRadius:26,fill:i=="wifi"?"#2EE6D6":"#2A3358",justifyContent:"center",alignItems:"center"});I(t,i,{s:20,f:i=="wifi"?"#0B1020":"#FFFFFF"})}const br=Fr(q,"Brightness",{width:"fill_container",height:36,cornerRadius:18,fill:"#2A3358"});Fr(br,"Level",{width:240,height:36,cornerRadius:18,fill:"#5B6590"});const st=V(s,"Notifications",{gap:4,padding:[10,12],height:"fill_container"});const lu=V(st,"Live update · sending",{gap:10,padding:16,cornerRadius:[24,24,6,6],fill:"#1E2748"});const h=H(lu,"Head",{gap:8});coinMini(h,20);T(h,"Quantum Safe · Sending",{name:"App",s:12,f:"#C9CFE8"});Sp(h);T(h,"now",{name:"Time",s:12,f:"#9AA3C7"});T(lu,"40,000 QC to Maya",{name:"Title",s:15,w:"600",f:"#FFFFFF"});const tr=Fr(lu,"Segmented progress",{width:"fill_container",gap:3});["signed","sent","confirming","final"].forEach((x,i)=>Fr(tr,"Segment · "+x,{width:"fill_container",height:6,cornerRadius:3,fill:i<2?"#2EE6D6":i==2?"#2EE6D688":"#2A3358"}));T(lu,"Confirming · 18 of 32 · about 1 s",{name:"Status",mono:true,s:11,f:"#9AA3C7"});const ac=Fr(lu,"Actions",{gap:18});T(ac,"Open",{name:"Action 1",s:13,w:"600",f:"#2EE6D6"});T(ac,"Copy signature",{name:"Action 2",s:13,w:"600",f:"#2EE6D6"});for(const[t,b,rad]of[["+2,000 QC received","From 3Fq…9aZ · 11:40",[6,6,6,6]],["282 hash keys left","Rotate before 24 · Tap to start",[6,6,24,24]]]){const n=H(st,"Notification · "+t,{gap:10,padding:16,cornerRadius:rad,fill:"#1E2748"});coinMini(n,32);const nt=V(n,"Text",{gap:2});T(nt,t,{name:"Title",s:14,w:"600",f:"#FFFFFF"});T(nt,b,{name:"Body",s:12,f:"#9AA3C7"});I(n,"chevron-down",{s:18,f:"#9AA3C7"})}botGest(s,"#FFFFFF")},"#0E1328");
ph("Notification · Android heads-up",412,420,s=>{sbAnd(s,{f:"#FFFFFF",notif:["shield"]});const n=V(s,"Heads-up",{gap:10,padding:16,cornerRadius:24,fill:"#1E2748"});Update(n,{width:388});const h=H(n,"Head",{gap:8});coinMini(h,20);T(h,"Quantum Safe",{name:"App",s:12,f:"#C9CFE8"});Sp(h);T(h,"now",{name:"Time",s:12,f:"#9AA3C7"});T(n,"New sign-in from Windows · Surabaya",{name:"Title",s:15,w:"600",f:"#FFFFFF"});T(n,"If this wasn't you, lock the vault now.",{name:"Body",s:13,f:"#C9CFE8"});const a=Fr(n,"Actions",{gap:18});T(a,"That was me",{name:"Action 1",s:13,w:"600",f:"#2EE6D6"});T(a,"Lock vault",{name:"Action 2",s:13,w:"600",f:"#FF6B6B"});homeGrid(s)},WP);
ph("Notification · Android status bar live chip",412,420,s=>{sbAnd(s,{f:"#FFFFFF",chip:"18/32"});homeGrid(s)},WP);
ph("Notification · Android lock screen",412,915,s=>{sbAnd(s,{f:"#FFFFFF"});const c=V(s,"Clock",{alignItems:"center",padding:[40,0,30,0]});T(c,"14",{name:"Hour",s:96,w:"600",f:"#FFFFFF"});T(c,"02",{name:"Minute",s:96,w:"600",f:"#2EE6D6"});const st=V(s,"Notifications",{gap:4,padding:[0,12],height:"fill_container",justifyContent:"end"});const n=H(st,"Live update",{gap:10,padding:16,cornerRadius:24,fill:"#1E2748"});coinMini(n,32);const nt=V(n,"Text",{gap:4});T(nt,"Sending 40,000 QC",{name:"Title",s:14,w:"600",f:"#FFFFFF"});const tr=Fr(nt,"Track",{width:"fill_container",height:4,cornerRadius:2,fill:"#2A3358"});Fr(tr,"Fill",{width:180,height:4,cornerRadius:2,fill:"#2EE6D6"});const fp=H(s,"Fingerprint area",{justifyContent:"center",padding:[24,0]});const f=Fr(fp,"Sensor",{width:56,height:56,cornerRadius:28,stroke:"#FFFFFF55",strokeWidth:1,justifyContent:"center",alignItems:"center"});I(f,"fingerprint-pattern",{s:26,f:"#FFFFFF"});botGest(s,"#FFFFFF")},WP);
ph("Foldable · cover screen live update",300,640,s=>{sbAnd(s,{f:"#FFFFFF"});const b=V(s,"Body",{gap:10,padding:16,height:"fill_container",justifyContent:"center",alignItems:"center"});coinMini(b,56);T(b,"Sending",{name:"Title",s:16,w:"600",f:"#FFFFFF"});T(b,"40,000 QC",{name:"Amount",mono:true,s:22,w:"600",f:"#FFFFFF"});const tr=Fr(b,"Track",{width:200,height:4,cornerRadius:2,fill:"#2A3358"});Fr(tr,"Fill",{width:110,height:4,cornerRadius:2,fill:"#2EE6D6"});botGest(s,"#FFFFFF")},"#000000");
ph("Watch · live transaction",198,242,s=>{const b=V(s,"Body",{gap:6,padding:12,height:"fill_container",alignItems:"center",justifyContent:"center"});const r=Fr(b,"Ring",{width:84,height:84,cornerRadius:42,stroke:"#2EE6D6",strokeWidth:4,justifyContent:"center",alignItems:"center"});coinMini(r,44);T(b,"18 / 32",{name:"Count",mono:true,s:13,f:"#2EE6D6"});T(b,"to Maya",{name:"Sub",s:12,f:"#9AA3C7"})},"#000000");
}

if(PART=="c"){
const pill=(s,name,w,h,rad,fn)=>{const top=H(s,"Pill area",{justifyContent:"center",padding:[8,0,0,0]});const p=Fr(top,name,{width:w,height:h,cornerRadius:rad,fill:"#000000",padding:[0,10],alignItems:"center",gap:8});fn(p);return p};
const prog=(p,w,f)=>{const t=Fr(p,"Track",{width:w,height:4,cornerRadius:2,fill:"#2A3358"});Fr(t,"Fill",{width:Math.round(w*f),height:4,cornerRadius:2,fill:"#2EE6D6"})};
ph("Android island · Xiaomi HyperIsland · compact",412,420,s=>{sbAnd(s,{f:"#FFFFFF"});pill(s,"HyperIsland · compact",230,34,17,p=>{coinMini(p,22);T(p,"Sending",{name:"Label",s:12,w:"600",f:"#FFFFFF"});Sp(p);T(p,"18/32",{name:"Count",mono:true,s:12,f:"#2EE6D6"})});homeGrid(s)},WP);
ph("Android island · Xiaomi HyperIsland · expanded",412,420,s=>{sbAnd(s,{f:"#FFFFFF"});const top=H(s,"Pill area",{justifyContent:"center",padding:[8,0,0,0]});const p=V(top,"HyperIsland · expanded",{width:380,gap:10,padding:16,cornerRadius:32,fill:"#000000"});const r=H(p,"Top",{gap:10});coinMini(r,34);const t=V(r,"Text",{gap:2});T(t,"40,000 QC to Maya",{name:"Title",w:"600",f:"#FFFFFF"});T(t,"Both keys signed",{name:"Sub",s:12,f:"#9AA3C7"});prog(p,348,.56);const a=Fr(p,"Actions",{width:"fill_container",gap:8});for(const l of["Open","Copy tx"]){const b=Fr(a,l,{width:"fill_container",height:36,cornerRadius:18,fill:"#1E2748",justifyContent:"center",alignItems:"center"});T(b,l,{name:"Label",s:13,w:"600",f:"#FFFFFF"})}homeGrid(s)},WP);
ph("Android island · OPPO/OnePlus Live Alerts capsule",412,420,s=>{sbAnd(s,{f:"#FFFFFF"});pill(s,"Live Alerts capsule",150,30,15,p=>{Fr(p,"Ring",{width:18,height:18,cornerRadius:9,stroke:"#2EE6D6",strokeWidth:2});T(p,"40,000 QC",{name:"Amount",mono:true,s:11,f:"#FFFFFF"})});homeGrid(s)},WP);
ph("Android island · OPPO/OnePlus Live Alerts expanded",412,420,s=>{sbAnd(s,{f:"#FFFFFF"});const top=H(s,"Pill area",{justifyContent:"center",padding:[8,0,0,0]});const p=V(top,"Live Alerts · expanded",{width:380,gap:8,padding:16,cornerRadius:28,fill:"#000000"});const r=H(p,"Top",{gap:10});coinMini(r,30);T(r,"Confirming",{name:"Title",w:"600",f:"#FFFFFF"});Sp(r);T(r,"~1 s",{name:"ETA",mono:true,s:12,f:"#2EE6D6"});const seg=Fr(p,"Steps",{width:"fill_container",gap:4});["Signed","Sent","Confirming","Final"].forEach((x,i)=>{const c=V(seg,x,{gap:4});Fr(c,"Bar",{width:"fill_container",height:4,cornerRadius:2,fill:i<3?"#2EE6D6":"#2A3358"});T(c,x,{name:"Label",s:10,f:i<3?"#FFFFFF":"#9AA3C7"})});homeGrid(s)},WP);
ph("Android island · Samsung Now Bar (lock screen)",412,915,s=>{sbAnd(s,{f:"#FFFFFF"});const c=V(s,"Clock",{alignItems:"center",padding:[60,0,0,0]});T(c,"14:02",{name:"Time",s:72,w:"500",f:"#FFFFFF"});T(c,"Fri, 26 September",{name:"Date",s:15,f:"#FFFFFF"});V(s,"Spacer",{height:"fill_container"});const nb=H(s,"Now Bar area",{justifyContent:"center",padding:[0,0,16,0]});const p=Fr(nb,"Now Bar",{width:300,height:52,cornerRadius:26,fill:"#1E2748",padding:[0,8],gap:10,alignItems:"center"});coinMini(p,36);const t=V(p,"Text",{gap:3});T(t,"Sending 40,000 QC",{name:"Title",s:13,w:"600",f:"#FFFFFF"});prog(t,180,.56);const dot=Fr(nb,"Pager",{gap:4});botGest(s,"#FFFFFF")},WP);
ph("Android island · Honor Magic Capsule",412,420,s=>{sbAnd(s,{f:"#FFFFFF"});pill(s,"Magic Capsule",200,32,16,p=>{coinMini(p,20);prog(p,90,.56);T(p,"56%",{name:"Pct",mono:true,s:11,f:"#2EE6D6"})});homeGrid(s)},WP);
ph("Android island · states: received / failed / needs approval",412,520,s=>{sbAnd(s,{f:"#FFFFFF"});const col=V(s,"States",{gap:14,padding:[12,16],alignItems:"center"});for(const[l,i,c,t]of[["received","arrow-down-left","#3DDC97","+2,000 QC"],["failed","x","#FF6B6B","Send failed"],["approve","fingerprint-pattern","#F5B94A","Approve on phone"],["low keys","key","#F5B94A","24 hash keys"]]){const p=Fr(col,"Pill · "+l,{height:34,cornerRadius:17,fill:"#000000",padding:[0,12],gap:8,alignItems:"center"});const w=Fr(p,"Icon",{width:22,height:22,cornerRadius:11,fill:c,justifyContent:"center",alignItems:"center"});I(w,i,{s:12,f:"#0B1020"});T(p,t,{name:"Label",s:12,w:"600",f:"#FFFFFF"})}const n=V(s,"Note",{padding:16});T(n,"Fallback when the OEM pill isn't available: Android 16 promoted Live Update notification + status bar chip.",{name:"Note",s:12,f:"#9AA3C7",wrap:true})},WP);
}
Print("IDS",out.join(","));
